### PR TITLE
Update homework.md

### PR DESCRIPTION
**Pull request by aleks-hyf**
The students got confused by this question, in fact the homework assignment doesn't totally make sense. Why are we getting user #1 every time? I don't know the best way to write the question, but I suggested at least 1 improvement. Please ping me if you want to come up with something better.

### CODE REVIEW

**Comment by senner008** [comment]
Agree, homework should make sense, regardless.
Additionally the searchProduct(productName), renderProducts() and getUser(user) don't belong in the ShoppingCart class

**Comment by alekslovestech** [comment]
OMG agreed! Let's try to fix it to make sense. Please @dpfernandes @ditlevHYF  can you help speed up the approval process? 
I should be able to 
1. Add new reviewers
2. merge my own PRs

There should of course be an approval step from someone else and that should just be ONE step, and not 3. 

Thanks! Hope we can iterate on this quicker and make the homework more sensible.

**Comment by ghost** [comment]
I approve!

**Comment by chklueter** [comment]
@dpfernandes @ditlevHYF can you take another look, approve this and merge?

**Review by ghost — APPROVED** [review]

**Pull request merged**
