### PR TITLE
Renamed instances of `master` to `main`

### PR DESCRIPTION
**Pull request by jason-vasilev**
Some links were updated but not all, as a couple still use `master` branch and will return 404 if renamed. Please, double-check if all loads.

### CODE REVIEW

**Review by dan-nil — APPROVED** [review]

**Comment by jason-vasilev** [comment]
@DanJecu could you merge it if you have write access? Thanks in advance ☺️

**Comment by dan-nil** [comment]
@jason-vasilev Unfortunately I don't have write access 😢

**Comment by jason-vasilev** [comment]
@shpomp I see you got the power to merge 🙏

**Comment by shpomp** [comment]
> @shpomp I see you got the power to merge 🙏

I don't... it was secretly taken away, but left for some others - try checking the org owners 😉 😀

**Review by shpomp — APPROVED** [review]
💖

**Comment by adamblanchard** [comment]
All staff members having merging powers, if you're ever in doubt, you can find someone from that list :)

I'm happy to be tagged and pinged 👌

**Pull request merged**
